version: "2"
services:
    qbittorrent:
        image: linuxserver/qbittorrent:14.2.0.99201912180418-6819-118af03ubuntu18.04.1-ls62
        container_name: qbittorrent
        environment:
            - PUID=1000
            - PGID=1000
            - TZ=Asia/Shanghai
            - UMASK_SET=022
            - WEBUI_PORT=8080
        volumes:
            - ./config/qbittorrent:/config
            - ./tmp/downloads:/downloads
        ports:
            - 51118:51118
            - 51118:51118/udp
            - 8080:8080
        restart: unless-stopped
